import puppeteer, { type Browser } from 'puppeteer';
import { AppError } from '../middleware/error.middleware.js';

/**
 * HTML → PDF, for report export.
 *
 * TWO DECISIONS WORTH KNOWING ABOUT.
 *
 * 1. We render OUR OWN HTML string, not the report route in the web app.
 *    Driving the SPA would mean authenticating a headless browser against our
 *    own API (carrying a manager's cookie into a subprocess), requiring the web
 *    app to be running and reachable from the API process, and inheriting its
 *    runtime — lazy chunks, web fonts, a highlighter that may not have loaded
 *    when we hit print. setContent renders a string we control, offline, and
 *    works whether or not the frontend is up. The cost is a second template
 *    that has to be kept honest against the on-screen report; it is deliberately
 *    built from the same ReportView the page renders, so it cannot show
 *    different NUMBERS, only a different layout.
 *
 * 2. Rendering is capped, not queued. BullMQ is right there, but a queued PDF
 *    needs somewhere to put the file, and the R2 storage those pdf_url /
 *    pdf_status columns were added for is not configured — so a job would
 *    finish with nowhere to write. Instead the request renders and streams the
 *    bytes back, with at most MAX_CONCURRENT renders in flight process-wide and
 *    the rest waiting their turn. A manager pressing "Download PDF" gets a
 *    file, not a poll.
 */

const MAX_CONCURRENT = 2;
// One browser, reused. Launching Chromium per request costs ~300ms and a lot
// of memory; keeping one is the difference between a pause and a stall.
let browserPromise: Promise<Browser> | null = null;

let active = 0;
const waiting: Array<() => void> = [];

async function acquire(): Promise<void> {
  if (active < MAX_CONCURRENT) {
    active += 1;
    return;
  }
  await new Promise<void>((resolve) => waiting.push(resolve));
  active += 1;
}

function release(): void {
  active -= 1;
  waiting.shift()?.();
}

async function getBrowser(): Promise<Browser> {
  if (!browserPromise) {
    browserPromise = puppeteer
      .launch({ headless: true, args: ['--no-sandbox', '--disable-dev-shm-usage'] })
      .catch((err: Error) => {
        // Let the next attempt try again rather than caching the failure.
        browserPromise = null;
        // The most likely cause by far in this repo: .npmrc skips the Chromium
        // download, so a fresh checkout has puppeteer but no browser. Say the
        // fix rather than leaking a library error.
        if (/Could not find|Browser was not found|ENOENT/i.test(err.message)) {
          throw new AppError(
            503,
            'PDF_UNAVAILABLE',
            'PDF export needs Chromium, which is not installed here. Run: npx puppeteer browsers install chrome',
          );
        }
        throw err;
      });
  }
  return browserPromise;
}

export async function renderPdf(html: string): Promise<Buffer> {
  await acquire();
  let page;
  try {
    const browser = await getBrowser();
    page = await browser.newPage();
    // `load` rather than `networkidle0`: the document has no network of its own
    // — everything it needs is inline — so waiting for idle would only add a
    // timeout's worth of nothing.
    await page.setContent(html, { waitUntil: 'load' });
    const pdf = await page.pdf({
      format: 'A4',
      printBackground: true,
      margin: { top: '14mm', bottom: '16mm', left: '12mm', right: '12mm' },
      displayHeaderFooter: true,
      headerTemplate: '<div></div>',
      footerTemplate:
        '<div style="width:100%;font-size:8px;color:#94a3b8;padding:0 12mm;display:flex;justify-content:space-between"><span>Generated by AssessIQ</span><span class="pageNumber"></span>/<span class="totalPages"></span></div>',
    });
    return Buffer.from(pdf);
  } finally {
    await page?.close().catch(() => {});
    release();
  }
}

/** Closed on shutdown so a killed API doesn't leave Chromium running. */
export async function closePdfBrowser(): Promise<void> {
  const current = browserPromise;
  browserPromise = null;
  if (current) await (await current).close().catch(() => {});
}
